#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


picom &
nitrogen --restore &
volumeicon &
batsignal -b -w "Battery at 15%"
$HOME/.config/polybar/launch.sh --forest
# xscreensaver -no-splash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 15
bspc config split ratio 0.60
bspc config focused_border_color '88C0D0'
bspc config focus_follows_pointer true

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
